
services:
  db:
    image: postgres:15
    container_name: booking_db
    ports:
      - "15432:5432"
    env_file:
      - docker.env

  redis:
    image: redis:7
    container_name: booking_redis
    env_file:
      - docker.env

  booking_app:
    build:
      context: .
    container_name: booking_app
    env_file:
      - docker.env
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    ports:
      - 8001:8000

  celery:
    build:
      context: .
    container_name: booking_celery
    env_file:
      - docker.env
    depends_on:
      - redis
    command: ["/booking/docker/celery.sh"]

